version: "3.7"

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=sqlite:///./backend/test.db
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
